# -*- coding: utf-8 -*-
"""EDA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_g_JFShO_QwRvbOv8FUk-2Tgegk8YXdK
"""

###
first check shape of the data imported
print(heroes.shape)
print(powers.shape)


#cheack properties of the data by these
heroes.head()
heroes.describe(include='all')
heroes.info()


# in case you have to cheak what is data with respect to colum in specified row then try this here "name" is collume name and "super man " is row in that column and we are searching same row in 'allingment' column
heroes.loc[heroes['name']=='Superman', 'Alignment']

#here we are checking unique entries in alignment columns and there number of count
heroes.Alignment.unique()
heroes.Alignment.value_counts()

#here we are counting missing values in data 
heroes.isnull().sum()
heroes.name.isna().sum() # and in specified column


# here we have droped a column unnamed 0 from data 
heroes.drop(['Unnamed: 0'], axis=1, inplace=True)

newtitanic = titanic.drop(['PassengerId','Name','SibSp','Parch','Ticket','Fare','Cabin','Embarked'],axis=1)

DataFrame.dropna(self, axis=0, how='any', thresh=None, subset=None, inplace=False)

# here we have find sum of publisher columns
heroes.Publisher.isna().sum()


# here we hafe replace all enteries which have value of '-' to 'unknown'
heroes.replace(to_replace='-', value='unknown', inplace=True)

# cheacking column 
heroes['Weight'].value_counts()

# replacing negative values in weights as there are already some nan values in weight culumns
heroes.replace(-99.0, np.nan, inplace=True)

# here we are creating new data frame by onlly height and weights
ht_wt = heroes[['Height', 'Weight']]

# impute these missing values mean or median here we have used median of rows to fill
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X = imputer.fit_transform(ht_wt)
heroes_h_w = pd.DataFrame(X, columns=ht_wt.columns)

heroes.columns # shows all the collumn names in given dataframe


# here we have droped columns of height and weight in heroes
heroes_without_h_w = heroes.drop(['Height','Weight'], axis=1)
# here we have merged the new columns in given data frame
heroes = pd.concat([heroes_without_h_w, heroes_h_w], axis=1)
heroes.head()

# here i have filled all na with mean which is 29 manually
clean_titanic = newtitanic.fillna(29)


heroes['Publisher'].values.count()# here we have count puvlisher
publisher_series = heroes['Publisher'].value_counts()


#
publishers = list(publisher_series.index)
publications = list((publisher_series/publisher_series.sum())*100)


# pie chart
plt.pie(publications,labels=publishers,colors=colors,
       autopct='%1.2f%%')

# plt.figure(figsize=(20,18), dpi=100)

fig = plt.gcf()
fig.set_size_inches(10,8)

plt.show()


import plotly.offline as py
import plotly.graph_objs as go
from plotly import tools

py.init_notebook_mode(connected=True)


###
# now git test is working or not check by simple command
a=10
print.a

### hi

alkd
###

